import commonjs from "@rollup/plugin-commonjs";
import nodeResolve from "@rollup/plugin-node-resolve";
import terser from "@rollup/plugin-terser";
import typescript from "@rollup/plugin-typescript";
import path from "node:path";
import url from "node:url";

/**
 * Whether Rollup is running in watch mode.
 *
 * The project uses this to enable source maps and to avoid minifying builds
 * that are intended for local debugging inside the Stream Deck app.
 */
const isWatching = !!process.env.ROLLUP_WATCH;

/**
 * Folder name of the Stream Deck plugin bundle generated by the build.
 */
const sdPlugin = "com.waleed-salama.turn-off-displays.sdPlugin";

/**
 * Rollup configuration for the Stream Deck backend entry point.
 *
 * The output is written directly into the `.sdPlugin` bundle so the same files
 * can be validated, linked, and packaged by the Stream Deck CLI.
 *
 * @type {import('rollup').RollupOptions}
 */
const config = {
	input: "src/plugin.ts",
	output: {
		file: `${sdPlugin}/bin/plugin.js`,
		sourcemap: isWatching,
		/**
		 * Converts relative sourcemap paths into absolute file URLs so VS Code can
		 * resolve breakpoints when attaching to the running Stream Deck plugin.
		 */
		sourcemapPathTransform: (relativeSourcePath, sourcemapPath) => {
			return url.pathToFileURL(path.resolve(path.dirname(sourcemapPath), relativeSourcePath)).href;
		}
	},
	plugins: [
		{
			name: "watch-externals",
			/**
			 * Watches manifest changes alongside the TypeScript sources so local
			 * development reloads reflect both code and metadata edits.
			 */
			buildStart: function () {
				this.addWatchFile(`${sdPlugin}/manifest.json`);
			},
		},
		typescript({
			mapRoot: isWatching ? "./" : undefined
		}),
		nodeResolve({
			browser: false,
			exportConditions: ["node"],
			preferBuiltins: true
		}),
		commonjs(),
		!isWatching && terser(),
		{
			name: "emit-module-package-file",
			/**
			 * Stream Deck runs the compiled backend as an ES module. Emitting a tiny
			 * `package.json` beside the bundle keeps Node's module loader aligned with
			 * the project's `type: module` setting after packaging.
			 */
			generateBundle() {
				this.emitFile({ fileName: "package.json", source: `{ "type": "module" }`, type: "asset" });
			}
		}
	]
};

export default config;
